services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    command: poetry run uvicorn src.app:app --host 0.0.0.0 --port ${PORT}
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      TWILIO_WHATSAPP_NUMBER: ${TWILIO_WHATSAPP_NUMBER}
      HOST: ${HOST}
      PORT: ${PORT}

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

